[profile.default]
optimizer = true
optimizer_runs = 100000
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'ds-test/=lib/ds-test/src/',
    'zodiac/=lib/zodiac/contracts/',
    'openzeppelin/=lib/zeppelin-solidity/contracts/',
    'gnosis-safe/=lib/safe-contracts/',
    'datetime/=lib/BokkyPooBahsDateTimeLibrary/contracts',

    '@gnosis.pm/safe-contracts/=lib/safe-contracts/',
    '@openzeppelin/contracts/=lib/zeppelin-solidity/contracts/'
]

# See more config options https://github.com/gakonst/foundry/tree/master/config