[profile.default]
solc_version = '0.8.17'
optimizer = true
optimizer_runs = 100000
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'openzeppelin/=lib/zeppelin-solidity/contracts/',
    'safe/=lib/safe-contracts/contracts',
    'datetime/=lib/BokkyPooBahsDateTimeLibrary/contracts',
    'llamapay/=lib/llamapay/contracts',
    '@gnosis.pm/safe-contracts/=lib/safe-contracts/',
    '@openzeppelin/contracts/=lib/zeppelin-solidity/contracts/'
]

# See more config options https://github.com/gakonst/foundry/tree/master/config
