on: [push]

name: ci

jobs:
  check:
    name: Tests (Foundry)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: forge test --force -vvv

      - name: Fork tests (mainnet)
        env:
          MAINNET_FORK_URL: ${{ secrets.MAINNET_FORK_URL }}
        run: forge test --match-contract FirmFactoryIntegrationTest --fork-url "$MAINNET_FORK_URL" -vvvv